#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail
shopt -s inherit_errexit

if [[ ! -d "ghc-8.8.4-cross" ]]
then
  atool -x ghc-8.8.4.tar.xz
  mv ghc-8.8.4 ghc-8.8.4-cross
  cp build-cross.mk ghc-8.8.4-cross/mk/build.mk
fi

cd ghc-8.8.4-cross
./configure --target=arm-linux-gnueabihf --enable-unregistered
make -j8
