#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail
shopt -s inherit_errexit

if [[ ! -d "ghc-8.8.4-native" ]]
then
  atool -x ghc-8.8.4.tar.xz
  mv ghc-8.8.4 ghc-8.8.4-native
  cp build-native.mk ghc-8.8.4-native/mk/build.mk
fi

cd ghc-8.8.4-native
./configure
make -j8
