#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail
shopt -s inherit_errexit

if [[ ! -d "ghc-8.8.4" ]]
then
  atool -x ghc-8.8.4.tar.xz
  cp build.mk ghc-8.8.4/mk/build.mk
fi

cd ghc-8.8.4
./configure --target=arm-linux-gnueabihf --enable-unregisterised
# make -j8
