#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail
shopt -s inherit_errexit


export BOOTSTRAP_HASKELL_NONINTERACTIVE=1
export BOOTSTRAP_HASKELL_GHC_VERSION=8.8.4
curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh

sudo apt-get install -y \
  gcc-arm-linux-gnueabihf \
  atool \
  ghc \
  cabal-install \
  llvm-7 \
  build-essential \
  git \
  autoconf \
  python3 \
  libgmp-dev \
  libncurses-dev

cabal new-install alex happy

if [[ ! -f "ghc-8.8.4.tar.xz" ]]
then
  curl -o ghc-8.8.4.tar.xz https://downloads.haskell.org/~ghc/8.8.4/ghc-8.8.4-src.tar.xz
fi
